- hosts: localhost
  gather_facts: False
  tasks:
    - name: create an ec2 instance
      ec2:
        region: us-east-1
        image: ami-1ecae776
        key_name: jenkins
        group: open-ssh
        instance_profile_name: CodeCommitPushPullRole
        instance_type: t2.micro
        wait: yes
        instance_tags:
          role: build-slave
        count: 1
        vpc_subnet_id: subnet-637bcb48
        assign_public_ip: True
      register: ec2