- hosts: localhost
  gather_facts: False
  tasks:
    - name: create an ec2 instance
      ec2:
        region: us-east-1
        image: ami-1ecae776
        key_name: shayne-labs
        group: inbound-ssh
        instance_profile_name: CodeCommitPushPullRole
        instance_type: t2.micro
        wait: yes
        instance_tags:
          role: builder
        count: 1
        vpc_subnet_id: subnet-4013507a
        assign_public_ip: True
      register: ec2